# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install pandas
          pip install sklearn
          pip install numpy
          pip install matplotlib
          pip install seaborn
      - run: |
          output=$(python auto_report_a1.py v2.21)
          output="${output//$'\n'/\\n}"
          output="${output// / }"
          echo "::set-output name=changelog::$output"
        id: step1
      - uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.DISCORD_KEY_REPORT }}
          method: 'POST'
          data: '{"content": "A1_${{ steps.step1.outputs.changelog }}"}'
      - run: |
          output=$(python auto_report_a2.py v2.21)
          output="${output//$'\n'/\\n}"
          output="${output// / }"
          echo "::set-output name=changelog::$output"
        id: step2
      - uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.DISCORD_KEY_REPORT }}
          method: 'POST'
          data: '{"content": "A2_${{ steps.step2.outputs.changelog }}"}'
      - run: |
          output=$(python auto_report_a3.py v2.21)
          output="${output//$'\n'/\\n}"
          output="${output// / }"
          echo "::set-output name=changelog::$output"
        id: step3
      - uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.DISCORD_KEY_REPORT }}
          method: 'POST'
          data: '{"content": "A3_${{ steps.step3.outputs.changelog }}"}'
      - run: |
          output=$(python auto_report_a4.py v2.21)
          output="${output//$'\n'/\\n}"
          output="${output// / }"
          echo "::set-output name=changelog::$output"
        id: step4
      - uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.DISCORD_KEY_REPORT }}
          method: 'POST'
          data: '{"content": "A4_${{ steps.step4.outputs.changelog }}"}'
      - run: |
          output=$(python auto_report_a5.py v2.21)
          output="${output//$'\n'/\\n}"
          output="${output// / }"
          echo "::set-output name=changelog::$output"
        id: step5
      - uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.DISCORD_KEY_REPORT }}
          method: 'POST'
          data: '{"content": "A5_${{ steps.step5.outputs.changelog }}"}'
      - run: |
          output=$(python auto_report_a6.py v2.21)
          output="${output//$'\n'/\\n}"
          output="${output// / }"
          echo "::set-output name=changelog::$output"
        id: step6
      - uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.DISCORD_KEY_REPORT }}
          method: 'POST'
          data: '{"content": "A6_${{ steps.step6.outputs.changelog }}"}'
      - run: |
          output=$(python auto_report_a7.py v2.21)
          output="${output//$'\n'/\\n}"
          output="${output// / }"
          echo "::set-output name=changelog::$output"
        id: step7
      - uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.DISCORD_KEY_REPORT }}
          method: 'POST'
          data: '{"content": "A7_${{ steps.step7.outputs.changelog }}"}'
      - run: |
          output=$(python auto_report_a8.py v2.21)
          output="${output//$'\n'/\\n}"
          output="${output// / }"
          echo "::set-output name=changelog::$output"
        id: step8
      - uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.DISCORD_KEY_REPORT }}
          method: 'POST'
          data: '{"content": "A8_${{ steps.step8.outputs.changelog }}"}'