# This is a basic workflow to help you get started with Actions

name: Run Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ subteam2_01_november ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install pandas
          pip install sklearn
          pip install numpy
          pip install matplotlib
          pip install seaborn
          pip install statsmodels 
          pip install mpmath
      - run: |
          output=$(python main.py v2.21)
          output="${output//$'\n'/\\n}"
          output="${output// / }"
          echo "::set-output name=changelog::$output"
        id: step1
      - run: |
          echo '${{ steps.step1.outputs.changelog }}'
